#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/live-installer.png /usr/share/icons/live-installer.xpm /usr/share/icons/emmi.png
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d live-installer remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
